contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    # CRUD
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/delete/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
]

project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include



urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categorie'



class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=200,blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, 
        blank=True, null=True
    )
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
    )


    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    

    class Meta:
        verbose_name = 'Contacto'
        

contact/forms.py
from contact.models import Contact
from django import forms


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = (
            'first_name', 'last_name', 'phone',
            'email', 'description', 'category',
        )
    
    

    # Quando eu quero validar varios campos
    def clean(self):
        cleaned_data = self.cleaned_data

        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = forms.ValidationError('O primeiro nome não pode ser igual ao segundo', code='invalid')

            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        #print(cleaned_data)
        return super().clean()


    # Quando eu quero validar apenas um campo
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        print(first_name)

        if first_name == 'ABC':
            #raise forms.ValidationError('Não digite ABC nesse campo')
            self.add_error(
            'first_name',
            forms.ValidationError(
                'Veio do ADD errors',
                code='invalid'
            )
        )


        return first_name

contact/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'contact/index.html')

contact/views/contact_forms.py
from django.http import Http404
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from contact.forms import ContactForm
from contact.models import Contact
from django.urls import reverse

from django.core.exceptions import ValidationError as validationError



def create(request):

    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST)
        
        context = {
            'form' : form,
            'form_action' : form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)


        return render(request, 'contact/create.html', context)



    context = {
        'form' : ContactForm()
    }

    return render(request, 'contact/create.html', context)



def update(request, contact_id):
    contact = get_object_or_404(Contact, contact_id, show=True)
    form_action = reverse('contact:update', args=(contact_id))


    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        
        context = {
            'form' : form,
            'form_action' : form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)


        return render(request, 'contact/create.html', context)



    context = {
        'form' : ContactForm(instance=contact),
        'form_action' : form_action,
    }

    return render(request, 'contact/create.html', context)

contact/views/contact_views.py
from django.http import Http404
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact

from django.core.paginator import Paginator



def index(request):

    contacts = Contact.objects\
        .filter(show=True)\
        .order_by('-id')


    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    #Ler uma consulta do banco de dados
    #print(contacts.query)

    context = {
        'page_obj': page_obj,
        'site_title' : 'Contacts - ',
    }

    return render(request, 'contact/index.html', context)



def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    

    if single_contact is None:
        raise Http404('Contact not found')

    context = {
        'contact': single_contact,
    }


    return render(
        request,
        'contact/contact.html',
        context
    )




def search(request):
    
   search_value = request.GET.get('q', '').strip()
   
   
   if search_value == '':
       return redirect('contact:index')

   contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value) 
        )\
        .order_by('-id')#[10:20]


   paginator = Paginator(contacts, 10)
   page_number = request.GET.get('page')
   page_obj = paginator.get_page(page_number)

   #print(contacts.query)
   context = {
       'page_obj': page_obj,
       'site_title' : 'Search - ',
       
       #Para mostrar o valor pesquisado no campo de busca
       'search_value': search_value,
   }

   return render(request, 'contact/index.html', context)

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>

        <p><b>ID: </b>{{ contact.id }}</p>
        <p><b>E-mail: </b>{{ contact.email }}</p>
        <p><b>Phone :</b>{{ contact.phone }}</p>
        <p><b>Description: </b>{{ contact.description }}</p>
        <p><b>Category: </b>{{ contact.category.name }}</p>

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
      
            <form action="" method="POST">
              {% csrf_token %}
      
              {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes">
                <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
              {% else %}
                <button class="btn btn-link btn-delete" type="submit">Delete</button>
              {% endif %}
            </form>
        </div>
    </div>
    
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="form-wrapper">

        <h2>Contact</h2>

        <form  action="{% url 'contact:create' %}" method="POST" enctype="multipart/form-data">

            {% csrf_token %}

            {% for field in form %}
                <div class="form-content">
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
           


            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>

        </form>
    </div>

{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contacts
                </caption>

                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Firstname</th>
                        <th class="table-header">Lastname</th>
                        <th class="table-header">Phone</th>
                        <th class="table-header">E-mail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a href="{% url 'contact:contact' contact.id %}">
                                    {{ contact.id }}
                                </a>
                            </td>
                            <td class="table-cel">
                                {{ contact.first_name }}                                                    
                            </td>
                            <td class="table-cel">
                                {{ contact.last_name }}                                                    
                            </td>
                            <td class="table-cel">
                                {{ contact.phone }}                                                    
                            </td>
                            <td class="table-cel">
                                {{ contact.email }}                                                    
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>    
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
                Nenhum contato encontrado
            </h1>
        </div>
    {% endif %}   
   

{% endblock content %}